config/routes.rb
Rails.application.routes.draw do
  # refer to schema, list id in bookmarks
  # bookmarks must be accessed through lists to create as seen in spec.
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end

  # You don't need to nest destroy as you don't need to access to lists
  resources :bookmarks, only: [:destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  # validates that the movie id is unique within the scope of the list
  validates :movie_id, uniqueness: { scope: :list_id, message: 'Already in list' }

  # has_many :lists, dependent: :destroy
  # has_many :movies, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 1 }
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  # associated of list reaching movies, through bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true
  validates :overview, :title, presence: true
  validates :title, length: { minimum: 1 }
  has_many :bookmarks
end

# Copy of fields #
# t.string :title
# t.string :overview
# t.string :post_url
# t.float :rating

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def new
    @list = List.new
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Movie Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
    <%# task in the () is passing an instance of the iterator placeholder task %>
    <%# creates link using title of task, path to task instance %>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= form_for(@list) do |f| %>
<%# must be form_for, for this exercise %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%# Submit %>
  <%= f.submit "Create List", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1>Header</h1>